### PR TITLE
GBE-577: make all commands implement getEmptyCommandRequest() method

### PR DESCRIPTION
**Pull request by janvenstermans**
Add interface CommandHasRequest, extending Command interface, with getEmptyCommandRequest() method

Change all Command implementations to CommandHasRequest

Always make order of methods:
1) getEmptyCommandRequest
2) getEmptyCommandResponse
3) execute

Always add @Override annotation

### CODE REVIEW

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by jandm** [comment]
Jan De Moerloose: +1 (binding)

**Comment by janvenstermans** [comment]
Vote successful:
Oliver May: +1 (binding)
Jan De Moerloose: +1 (binding)

Jan Venstermans: +1

**Pull request merged**
