### PR TITLE
MAJ1129-Update_copyright_headers

### PR DESCRIPTION
**Pull request by streulma**

### CODE REVIEW

**Comment by oliverm-be** [comment]
For furure commits, please provide the JIRA issue in the format: KEY-number. In this case: MAJ-1129, otherwise the link between JIRA and GIT is lost.

**Comment by janvenstermans** [comment]
Jan Venstermans : +1

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by jandm** [comment]
+1 (binding)

**Pull request merged**
