### PR TITLE
MAJ-1181: bugfix filter of geomajasContext*.xml

### PR DESCRIPTION
**Pull request by janvenstermans**

### CODE REVIEW

**Comment by janvenstermans** [comment]
As a test, run on Jenkins: http://ci.geomajas.org/jenkins/job/Geomajas%20Project%20Server%20MAJ-1181-v2/4/

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by hkristof** [comment]
Kristof: +1 (binding)

**Comment by pieterdg** [comment]
+1

**Comment by janvenstermans** [comment]
Vote count: 
Kristof Heirwegh: +1 (binding)
Pieter De Graef: +1 (binding)
Jan Venstermans: +1

vote is successful

**Pull request merged**
