### PR TITLE
Gbe 536 copy development guide server side

### PR DESCRIPTION
**Pull request by janvenstermans**
Two step process:
1) copy all files from developer guide
2) remove elements that only refer to client  
+  client-generated listing elements: copy resource elements to other server modules or copy source to documentation file.

### CODE REVIEW

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by janvenstermans** [comment]
travis fail: wrong configuration, no more than 1000 lines output.

**Comment by pieterdg** [comment]
Pieter De Graef: +1 (binding).

Very nice work indeed!

2015-02-11 9:07 GMT+01:00 janvenstermans <notifications@github.com>:

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by janvenstermans** [comment]
Vote successful:
Oliver May: +1 (binding)
Pieter De Graef: +1 (binding)

Jan Venstermans: +1

**Pull request merged**
